/*
  # Seed Sample Data for AutoJobr

  1. Sample Jobs
    - Add realistic job listings from various companies
    - Include different job types, locations, and salary ranges

  2. Sample Data
    - Tech companies and startups
    - Various experience levels
    - Remote and on-site positions
*/

-- Insert sample jobs
INSERT INTO jobs (
  id,
  title,
  company,
  location,
  job_type,
  salary_min,
  salary_max,
  salary_currency,
  description,
  requirements,
  benefits,
  posted_date,
  is_remote,
  tags,
  source,
  application_url,
  is_active
) VALUES 
(
  uuid_generate_v4(),
  'Senior Software Engineer',
  'Google',
  'Mountain View, CA',
  'full-time',
  150000,
  250000,
  'USD',
  'We are looking for a Senior Software Engineer to join our Search team. You will work on large-scale distributed systems that serve billions of users worldwide.',
  ARRAY['Bachelor''s degree in Computer Science or equivalent', '5+ years of software development experience', 'Experience with Java, Python, or C++', 'Experience with distributed systems', 'Strong problem-solving skills'],
  ARRAY['Competitive salary and equity', 'Comprehensive health insurance', 'Free meals and snacks', '20% time for personal projects', 'Learning and development budget'],
  now() - interval '1 day',
  false,
  ARRAY['Java', 'Python', 'Distributed Systems', 'Search'],
  'linkedin',
  'https://careers.google.com/jobs/results/123456789',
  true
),
(
  uuid_generate_v4(),
  'Frontend Developer',
  'Meta',
  'Menlo Park, CA',
  'full-time',
  130000,
  200000,
  'USD',
  'Join our Frontend Infrastructure team to build the next generation of web experiences for billions of users across Facebook, Instagram, and WhatsApp.',
  ARRAY['Bachelor''s degree in Computer Science or related field', '3+ years of frontend development experience', 'Expert knowledge of React, JavaScript, and TypeScript', 'Experience with modern build tools and CI/CD', 'Understanding of web performance optimization'],
  ARRAY['Stock options', 'Health, dental, and vision insurance', 'Flexible work arrangements', 'Professional development opportunities', 'Free transportation'],
  now() - interval '2 days',
  true,
  ARRAY['React', 'JavaScript', 'TypeScript', 'Frontend'],
  'indeed',
  'https://www.metacareers.com/jobs/987654321',
  true
),
(
  uuid_generate_v4(),
  'DevOps Engineer',
  'Amazon',
  'Seattle, WA',
  'full-time',
  140000,
  220000,
  'USD',
  'AWS is looking for a DevOps Engineer to help build and maintain our cloud infrastructure. You''ll work with cutting-edge technologies to ensure reliability and scalability.',
  ARRAY['Bachelor''s degree in Engineering or Computer Science', '4+ years of DevOps or Infrastructure experience', 'Strong experience with AWS services', 'Proficiency in Docker, Kubernetes, and Terraform', 'Experience with monitoring and logging tools'],
  ARRAY['Competitive compensation', 'Stock purchase plan', 'Comprehensive benefits package', 'Career development programs', 'Flexible work options'],
  now() - interval '3 days',
  false,
  ARRAY['AWS', 'Docker', 'Kubernetes', 'Terraform', 'DevOps'],
  'glassdoor',
  'https://amazon.jobs/en/jobs/123456',
  true
),
(
  uuid_generate_v4(),
  'Full Stack Developer',
  'Stripe',
  'San Francisco, CA',
  'full-time',
  160000,
  240000,
  'USD',
  'Help us build the economic infrastructure for the internet. You''ll work on products that handle billions of dollars in transactions.',
  ARRAY['Strong programming skills in Ruby, Python, or JavaScript', '3+ years of full-stack development experience', 'Experience with databases and API design', 'Understanding of payment systems (preferred)', 'Strong communication skills'],
  ARRAY['Equity package', 'Health and wellness benefits', 'Unlimited PTO', 'Learning stipend', 'Remote work flexibility'],
  now() - interval '4 days',
  true,
  ARRAY['Ruby', 'Python', 'JavaScript', 'Full Stack', 'Payments'],
  'workday',
  'https://stripe.com/jobs/listing/full-stack-engineer',
  true
),
(
  uuid_generate_v4(),
  'Data Scientist',
  'Netflix',
  'Los Gatos, CA',
  'full-time',
  170000,
  280000,
  'USD',
  'Join our Data Science team to help personalize the Netflix experience for 200+ million members worldwide using machine learning and analytics.',
  ARRAY['PhD or Master''s in Statistics, Computer Science, or related field', '4+ years of data science experience', 'Strong skills in Python, R, and SQL', 'Experience with machine learning frameworks', 'Experience with A/B testing and experimentation'],
  ARRAY['Stock options', 'Comprehensive health coverage', 'Unlimited vacation', 'Parental leave', 'Professional development budget'],
  now() - interval '5 days',
  false,
  ARRAY['Python', 'R', 'Machine Learning', 'Statistics', 'A/B Testing'],
  'linkedin',
  'https://jobs.netflix.com/jobs/123456789',
  true
),
(
  uuid_generate_v4(),
  'Software Engineer',
  'Infosys',
  'Bangalore, India',
  'full-time',
  800000,
  1500000,
  'INR',
  'Join our digital transformation team to work on cutting-edge projects for global clients. Experience with cloud technologies and agile methodologies preferred.',
  ARRAY['Bachelor''s degree in Computer Science or Engineering', '2+ years of software development experience', 'Proficiency in Java, .NET, or Python', 'Knowledge of cloud platforms (AWS/Azure)', 'Strong analytical and problem-solving skills'],
  ARRAY['Competitive salary', 'Health insurance', 'Flexible working hours', 'Training and certification programs', 'Career growth opportunities'],
  now() - interval '6 days',
  false,
  ARRAY['Java', '.NET', 'Python', 'Cloud', 'Agile'],
  'naukri',
  'https://www.infosys.com/careers/job-listing/123456',
  true
),
(
  uuid_generate_v4(),
  'Product Manager',
  'Airbnb',
  'San Francisco, CA',
  'full-time',
  180000,
  260000,
  'USD',
  'Lead product strategy and execution for our host experience platform. Work cross-functionally to deliver products that delight millions of hosts worldwide.',
  ARRAY['Bachelor''s degree in Business, Engineering, or related field', '5+ years of product management experience', 'Experience with consumer-facing products', 'Strong analytical and communication skills', 'Experience with A/B testing and data analysis'],
  ARRAY['Competitive salary and equity', 'Annual travel credit', 'Health and wellness benefits', 'Professional development budget', 'Flexible work arrangements'],
  now() - interval '7 days',
  true,
  ARRAY['Product Management', 'Strategy', 'Analytics', 'Consumer Products'],
  'linkedin',
  'https://careers.airbnb.com/positions/123456',
  true
),
(
  uuid_generate_v4(),
  'UX Designer',
  'Figma',
  'San Francisco, CA',
  'full-time',
  140000,
  200000,
  'USD',
  'Help shape the future of design tools. Work on products used by millions of designers and developers worldwide.',
  ARRAY['Bachelor''s degree in Design, HCI, or related field', '4+ years of UX design experience', 'Proficiency in Figma, Sketch, and prototyping tools', 'Strong portfolio demonstrating design process', 'Experience with user research and testing'],
  ARRAY['Equity package', 'Health and dental insurance', 'Design equipment budget', 'Learning and development stipend', 'Flexible PTO'],
  now() - interval '8 days',
  false,
  ARRAY['UX Design', 'Figma', 'Prototyping', 'User Research'],
  'indeed',
  'https://www.figma.com/careers/job/123456',
  true
),
(
  uuid_generate_v4(),
  'Machine Learning Engineer',
  'OpenAI',
  'San Francisco, CA',
  'full-time',
  200000,
  350000,
  'USD',
  'Join our research team to develop and deploy large-scale machine learning systems. Work on cutting-edge AI research and applications.',
  ARRAY['PhD or Master''s in Computer Science, Machine Learning, or related field', '3+ years of ML engineering experience', 'Strong programming skills in Python and PyTorch/TensorFlow', 'Experience with distributed systems and cloud platforms', 'Publications in top-tier ML conferences (preferred)'],
  ARRAY['Competitive salary and equity', 'Comprehensive health benefits', 'Research publication support', 'Conference attendance budget', 'Flexible work arrangements'],
  now() - interval '9 days',
  true,
  ARRAY['Machine Learning', 'Python', 'PyTorch', 'AI Research'],
  'workday',
  'https://openai.com/careers/machine-learning-engineer',
  true
),
(
  uuid_generate_v4(),
  'Backend Engineer',
  'Spotify',
  'Stockholm, Sweden',
  'full-time',
  80000,
  120000,
  'EUR',
  'Build and scale backend services that power music discovery for 400+ million users. Work with microservices, event-driven architecture, and real-time systems.',
  ARRAY['Bachelor''s degree in Computer Science or equivalent', '3+ years of backend development experience', 'Strong skills in Java, Scala, or Python', 'Experience with microservices and distributed systems', 'Knowledge of databases and caching systems'],
  ARRAY['Competitive salary and equity', 'Spotify Premium for family', 'Health and wellness benefits', 'Parental leave', 'Learning and development budget'],
  now() - interval '10 days',
  false,
  ARRAY['Java', 'Scala', 'Microservices', 'Backend', 'Music'],
  'glassdoor',
  'https://www.lifeatspotify.com/jobs/123456',
  true
);